<?php

use common\src\migration\TableMigration;

/**
 * Class m190512_034041_create_table_city
 */
class m190512_034041_create_table_city extends TableMigration
{
    /**
     * @inheritDoc
     */
    protected function getTableName(): string
    {
        return 'city';
    }

    /**
     * @inheritDoc
     */
    protected function getTableColumns(): array
    {
        return [
            'id' => $this->primaryKey(),
            'name' => $this->string()->notNull(),
        ];
    }

    /**
     * @inheritDoc
     */
    protected function getTableColumnValues(): array
    {
        return [
            ['id' => 1, 'name' => 'Kirksville'],
            ['id' => 2, 'name' => 'Abilene'],
            ['id' => 3, 'name' => 'Tifton'],
            ['id' => 4, 'name' => 'San Francisco'],
            ['id' => 5, 'name' => 'Alamosa'],
            ['id' => 6, 'name' => 'Garden City'],
            ['id' => 7, 'name' => 'Richfield'],
            ['id' => 8, 'name' => 'Chicago'],
            ['id' => 9, 'name' => 'Adrian'],
            ['id' => 10, 'name' => 'Orlando'],
            ['id' => 11, 'name' => 'Decatur'],
            ['id' => 12, 'name' => 'Wright-Patterson AFB'],
            ['id' => 13, 'name' => 'Normal'],
            ['id' => 14, 'name' => 'Montgomery'],
            ['id' => 15, 'name' => 'Palmer'],
            ['id' => 16, 'name' => 'Anchorage'],
            ['id' => 17, 'name' => 'Albany'],
            ['id' => 18, 'name' => 'New Haven'],
            ['id' => 19, 'name' => 'Albion'],
            ['id' => 20, 'name' => 'Reading'],
            ['id' => 21, 'name' => 'Lorman'],
            ['id' => 22, 'name' => 'Philippi'],
            ['id' => 23, 'name' => 'Alfred'],
            ['id' => 24, 'name' => 'Pippa Passes'],
            ['id' => 25, 'name' => 'Meadville'],
            ['id' => 26, 'name' => 'Waterloo'],
            ['id' => 27, 'name' => 'Columbia'],
            ['id' => 28, 'name' => 'San Diego'],
            ['id' => 29, 'name' => 'Alma'],
            ['id' => 30, 'name' => 'Milwaukee'],
            ['id' => 31, 'name' => 'Garland'],
            ['id' => 32, 'name' => 'Nashville'],
            ['id' => 33, 'name' => 'Los Angeles'],
            ['id' => 34, 'name' => 'Springfield'],
            ['id' => 35, 'name' => 'Washington'],
            ['id' => 36, 'name' => 'Amherst'],
            ['id' => 37, 'name' => 'Anderson'],
            ['id' => 38, 'name' => 'Berrien Springs'],
            ['id' => 39, 'name' => 'San Angelo'],
            ['id' => 40, 'name' => 'Paxton'],
            ['id' => 41, 'name' => 'Yellow Springs'],
            ['id' => 42, 'name' => 'Culver City'],
            ['id' => 43, 'name' => 'Keene'],
            ['id' => 44, 'name' => 'Santa Barbara'],
            ['id' => 45, 'name' => 'Seattle'],
            ['id' => 46, 'name' => 'Mount Hope'],
            ['id' => 47, 'name' => 'Oakwood'],
            ['id' => 48, 'name' => 'Boone'],
            ['id' => 49, 'name' => 'Grand Rapids'],
            ['id' => 50, 'name' => 'Glenside'],
            ['id' => 51, 'name' => 'Orange'],
            ['id' => 52, 'name' => 'Phoenix'],
            ['id' => 53, 'name' => 'Tempe'],
            ['id' => 54, 'name' => 'Little Rock'],
            ['id' => 55, 'name' => 'Jonesboro'],
            ['id' => 56, 'name' => 'Russellville'],
            ['id' => 57, 'name' => 'Arlington'],
            ['id' => 58, 'name' => 'Savannah'],
            ['id' => 59, 'name' => 'Cincinnati'],
            ['id' => 60, 'name' => 'Pasadena'],
            ['id' => 61, 'name' => 'Wilmore'],
            ['id' => 62, 'name' => 'Ashland'],
            ['id' => 63, 'name' => 'Worcester'],
            ['id' => 64, 'name' => 'Athens'],
            ['id' => 65, 'name' => 'Atlanta'],
            ['id' => 66, 'name' => 'Auburn'],
            ['id' => 67, 'name' => 'Minneapolis'],
            ['id' => 68, 'name' => 'Augusta'],
            ['id' => 69, 'name' => 'Rock Island'],
            ['id' => 70, 'name' => 'Sioux Falls'],
            ['id' => 71, 'name' => 'Aurora'],
            ['id' => 72, 'name' => 'Sherman'],
            ['id' => 73, 'name' => 'Clarksville'],
            ['id' => 74, 'name' => 'Ave Maria'],
            ['id' => 75, 'name' => 'Danville'],
            ['id' => 76, 'name' => 'Kansas City'],
            ['id' => 77, 'name' => 'Azusa'],
            ['id' => 78, 'name' => 'Babson Park'],
            ['id' => 79, 'name' => 'Muskogee'],
            ['id' => 80, 'name' => 'Flint'],
            ['id' => 81, 'name' => 'Baldwin City'],
            ['id' => 82, 'name' => 'Berea'],
            ['id' => 83, 'name' => 'Muncie'],
            ['id' => 84, 'name' => 'New York City'],
            ['id' => 85, 'name' => 'Memphis'],
            ['id' => 86, 'name' => 'San Antonio'],
            ['id' => 87, 'name' => 'Haviland'],
            ['id' => 88, 'name' => 'Annandale-on-Hudson'],
            ['id' => 89, 'name' => 'Great Barrington'],
            ['id' => 90, 'name' => 'St. Louis'],
            ['id' => 91, 'name' => 'Miami'],
            ['id' => 92, 'name' => 'Wilson'],
            ['id' => 93, 'name' => 'Kenmore'],
            ['id' => 94, 'name' => 'Lewiston'],
            ['id' => 95, 'name' => 'Longmeadow'],
            ['id' => 96, 'name' => 'Boston'],
            ['id' => 97, 'name' => 'Houston'],
            ['id' => 98, 'name' => 'Waco'],
            ['id' => 99, 'name' => 'Leesburg'],
            ['id' => 100, 'name' => 'Jackson'],
            ['id' => 101, 'name' => 'Louisville'],
            ['id' => 102, 'name' => 'Bellevue'],
            ['id' => 103, 'name' => 'Green Bay'],
            ['id' => 104, 'name' => 'Belmont'],
            ['id' => 105, 'name' => 'Beloit'],
            ['id' => 106, 'name' => 'Bemidji'],
            ['id' => 107, 'name' => 'Atchison'],
            ['id' => 108, 'name' => 'Lisle'],
            ['id' => 109, 'name' => 'Greensboro'],
            ['id' => 110, 'name' => 'Bennington'],
            ['id' => 111, 'name' => 'Waltham'],
            ['id' => 112, 'name' => 'Mount Berry'],
            ['id' => 113, 'name' => 'Bethany'],
            ['id' => 114, 'name' => 'Lindsborg'],
            ['id' => 115, 'name' => 'Mankato'],
            ['id' => 116, 'name' => 'North Newton'],
            ['id' => 117, 'name' => 'Mishawaka'],
            ['id' => 118, 'name' => 'St. Paul'],
            ['id' => 119, 'name' => 'McKenzie'],
            ['id' => 120, 'name' => 'Anaheim'],
            ['id' => 121, 'name' => 'Daytona Beach'],
            ['id' => 122, 'name' => 'Vestal'],
            ['id' => 123, 'name' => 'La Mirada'],
            ['id' => 124, 'name' => 'Birmingham'],
            ['id' => 125, 'name' => 'Bismarck'],
            ['id' => 126, 'name' => 'Spearfish'],
            ['id' => 127, 'name' => 'Carlinville'],
            ['id' => 128, 'name' => 'Quincy'],
            ['id' => 129, 'name' => 'Bloomfield'],
            ['id' => 130, 'name' => 'Bloomsburg'],
            ['id' => 131, 'name' => 'Blue Mountain'],
            ['id' => 132, 'name' => 'Bluefield'],
            ['id' => 133, 'name' => 'Bluffton'],
            ['id' => 134, 'name' => 'Greenville'],
            ['id' => 135, 'name' => 'Boise'],
            ['id' => 136, 'name' => 'Chestnut Hill'],
            ['id' => 137, 'name' => 'Brookline'],
            ['id' => 138, 'name' => 'Brunswick'],
            ['id' => 139, 'name' => 'Bowie'],
            ['id' => 140, 'name' => 'Bowling Green'],
            ['id' => 141, 'name' => 'Peoria'],
            ['id' => 142, 'name' => 'Irvine'],
            ['id' => 143, 'name' => 'Lake Jackson'],
            ['id' => 144, 'name' => 'Gainesville'],
            ['id' => 145, 'name' => 'Owensboro'],
            ['id' => 146, 'name' => 'Brevard'],
            ['id' => 147, 'name' => 'Mount Vernon'],
            ['id' => 148, 'name' => 'Sioux City'],
            ['id' => 149, 'name' => 'Bethpage'],
            ['id' => 150, 'name' => 'Bridgewater'],
            ['id' => 151, 'name' => 'Provo'],
            ['id' => 152, 'name' => 'Laie'],
            ['id' => 153, 'name' => 'Rexburg'],
            ['id' => 154, 'name' => 'Brooklyn'],
            ['id' => 155, 'name' => 'Fort Lauderdale'],
            ['id' => 156, 'name' => 'Salina'],
            ['id' => 157, 'name' => 'Providence'],
            ['id' => 158, 'name' => 'Dayton'],
            ['id' => 159, 'name' => 'Lincoln'],
            ['id' => 160, 'name' => 'Buffalo'],
            ['id' => 161, 'name' => 'Smithfield'],
            ['id' => 162, 'name' => 'Bryn Athyn'],
            ['id' => 163, 'name' => 'Bryn Mawr'],
            ['id' => 164, 'name' => 'Lewisburg'],
            ['id' => 165, 'name' => 'Storm Lake'],
            ['id' => 166, 'name' => 'Indianapolis'],
            ['id' => 167, 'name' => 'Concord'],
            ['id' => 168, 'name' => 'Radnor'],
            ['id' => 169, 'name' => 'Langhorne'],
            ['id' => 170, 'name' => 'Caldwell'],
            ['id' => 171, 'name' => 'Riverside'],
            ['id' => 172, 'name' => 'Valencia'],
            ['id' => 173, 'name' => 'Thousand Oaks'],
            ['id' => 174, 'name' => 'San Luis Obispo'],
            ['id' => 175, 'name' => 'Pomona'],
            ['id' => 176, 'name' => 'Camarillo'],
            ['id' => 177, 'name' => 'Vallejo'],
            ['id' => 178, 'name' => 'San Marcos'],
            ['id' => 179, 'name' => 'Turlock'],
            ['id' => 180, 'name' => 'Bakersfield'],
            ['id' => 181, 'name' => 'Chico'],
            ['id' => 182, 'name' => 'Carson'],
            ['id' => 183, 'name' => 'Hayward'],
            ['id' => 184, 'name' => 'Fresno'],
            ['id' => 185, 'name' => 'Fullerton'],
            ['id' => 186, 'name' => 'Long Beach'],
            ['id' => 187, 'name' => 'Seaside'],
            ['id' => 188, 'name' => 'Northridge'],
            ['id' => 189, 'name' => 'Sacramento'],
            ['id' => 190, 'name' => 'San Bernardino'],
            ['id' => 191, 'name' => 'California'],
            ['id' => 192, 'name' => 'Whiting'],
            ['id' => 193, 'name' => 'Cambridge'],
            ['id' => 194, 'name' => 'Lawton'],
            ['id' => 195, 'name' => 'Buies Creek'],
            ['id' => 196, 'name' => 'Campbellsville'],
            ['id' => 197, 'name' => 'Columbus'],
            ['id' => 198, 'name' => 'Laurel'],
            ['id' => 199, 'name' => 'Northfield'],
            ['id' => 200, 'name' => 'Pittsburgh'],
            ['id' => 201, 'name' => 'Helena'],
            ['id' => 202, 'name' => 'Waukesha'],
            ['id' => 203, 'name' => 'Jefferson City'],
            ['id' => 204, 'name' => 'Kenosha'],
            ['id' => 205, 'name' => 'Cleveland'],
            ['id' => 206, 'name' => 'Castleton'],
            ['id' => 207, 'name' => 'Salisbury'],
            ['id' => 208, 'name' => 'Cazenovia'],
            ['id' => 209, 'name' => 'Allentown'],
            ['id' => 210, 'name' => 'Cedarville'],
            ['id' => 211, 'name' => 'Shreveport'],
            ['id' => 212, 'name' => 'Hackettstown'],
            ['id' => 213, 'name' => 'Conway'],
            ['id' => 214, 'name' => 'McPherson'],
            ['id' => 215, 'name' => 'Moberly'],
            ['id' => 216, 'name' => 'Pella'],
            ['id' => 217, 'name' => 'New Britain'],
            ['id' => 218, 'name' => 'Fayette'],
            ['id' => 219, 'name' => 'Mount Pleasant'],
            ['id' => 220, 'name' => 'Summerdale'],
            ['id' => 221, 'name' => 'Wilberforce'],
            ['id' => 222, 'name' => 'Ellensburg'],
            ['id' => 223, 'name' => 'Centralia'],
            ['id' => 224, 'name' => 'Chadron'],
            ['id' => 225, 'name' => 'Addison'],
            ['id' => 226, 'name' => 'Honolulu'],
            ['id' => 227, 'name' => 'Burlington'],
            ['id' => 228, 'name' => 'Charleston'],
            ['id' => 229, 'name' => 'Philadelphia'],
            ['id' => 230, 'name' => 'Cheyney'],
            ['id' => 231, 'name' => 'Marianna'],
            ['id' => 232, 'name' => 'Murfreesboro'],
            ['id' => 233, 'name' => 'Newport News'],
            ['id' => 234, 'name' => 'Orangeburg'],
            ['id' => 235, 'name' => 'Claremont'],
            ['id' => 236, 'name' => 'Clarion'],
            ['id' => 237, 'name' => 'Dubuque'],
            ['id' => 238, 'name' => 'Clarks Summit'],
            ['id' => 239, 'name' => 'Omaha'],
            ['id' => 240, 'name' => 'Potsdam'],
            ['id' => 241, 'name' => 'Morrow'],
            ['id' => 242, 'name' => 'Pineville'],
            ['id' => 243, 'name' => 'Howell'],
            ['id' => 244, 'name' => 'Clemson'],
            ['id' => 245, 'name' => 'Overland Park'],
            ['id' => 246, 'name' => 'Cedar Rapids'],
            ['id' => 247, 'name' => 'San Jose'],
            ['id' => 248, 'name' => 'Hartsville'],
            ['id' => 249, 'name' => 'Waterville'],
            ['id' => 250, 'name' => 'New London'],
            ['id' => 251, 'name' => 'Hamilton'],
            ['id' => 252, 'name' => 'Detroit'],
            ['id' => 253, 'name' => 'Ocala'],
            ['id' => 254, 'name' => 'The Bronx'],
            ['id' => 255, 'name' => 'Chicopee'],
            ['id' => 256, 'name' => 'St. Joseph'],
            ['id' => 257, 'name' => 'Morristown'],
            ['id' => 258, 'name' => 'Las Vegas'],
            ['id' => 259, 'name' => 'Rutland'],
            ['id' => 260, 'name' => 'Staten Island'],
            ['id' => 261, 'name' => 'Bar Harbor'],
            ['id' => 262, 'name' => 'Point Lookout'],
            ['id' => 263, 'name' => 'Williamsburg'],
            ['id' => 264, 'name' => 'Lakewood'],
            ['id' => 265, 'name' => 'Colorado Springs'],
            ['id' => 266, 'name' => 'Grand Junction'],
            ['id' => 267, 'name' => 'Golden'],
            ['id' => 268, 'name' => 'Fort Collins'],
            ['id' => 269, 'name' => 'Pueblo'],
            ['id' => 270, 'name' => 'Pasco'],
            ['id' => 271, 'name' => 'Glendale'],
            ['id' => 272, 'name' => 'Tarzana'],
            ['id' => 273, 'name' => 'Moorhead'],
            ['id' => 274, 'name' => 'Selma'],
            ['id' => 275, 'name' => 'Bronxville'],
            ['id' => 276, 'name' => 'Ann Arbor'],
            ['id' => 277, 'name' => 'River Forest'],
            ['id' => 278, 'name' => 'Austin'],
            ['id' => 279, 'name' => 'Mequon'],
            ['id' => 280, 'name' => 'Seward'],
            ['id' => 281, 'name' => 'Portland'],
            ['id' => 282, 'name' => 'Spartanburg'],
            ['id' => 283, 'name' => 'Baltimore'],
            ['id' => 284, 'name' => 'Salem'],
            ['id' => 285, 'name' => 'Ithaca'],
            ['id' => 286, 'name' => 'Nevada'],
            ['id' => 287, 'name' => 'Lookout Mountain'],
            ['id' => 288, 'name' => 'Bloomfield Hills'],
            ['id' => 289, 'name' => 'Dallas'],
            ['id' => 290, 'name' => 'Rochester'],
            ['id' => 291, 'name' => 'Paragould'],
            ['id' => 292, 'name' => 'St. Bonifacius'],
            ['id' => 293, 'name' => 'Canton'],
            ['id' => 294, 'name' => 'Lebanon'],
            ['id' => 295, 'name' => 'Long Island City'],
            ['id' => 296, 'name' => 'Milton'],
            ['id' => 297, 'name' => 'Madison'],
            ['id' => 298, 'name' => 'Mitchell'],
            ['id' => 299, 'name' => 'Dalton'],
            ['id' => 300, 'name' => 'Hanover'],
            ['id' => 301, 'name' => 'Davidson'],
            ['id' => 302, 'name' => 'Elkins'],
            ['id' => 303, 'name' => 'Johnson City'],
            ['id' => 304, 'name' => 'Franklin'],
            ['id' => 305, 'name' => 'Defiance'],
            ['id' => 306, 'name' => 'Dover'],
            ['id' => 307, 'name' => 'Doylestown'],
            ['id' => 308, 'name' => 'Granville'],
            ['id' => 309, 'name' => 'Denver'],
            ['id' => 310, 'name' => 'Greencastle'],
            ['id' => 311, 'name' => 'Des Moines'],
            ['id' => 312, 'name' => 'Center Valley'],
            ['id' => 313, 'name' => 'Carlisle'],
            ['id' => 314, 'name' => 'Dickinson'],
            ['id' => 315, 'name' => 'New Orleans'],
            ['id' => 316, 'name' => 'St. George'],
            ['id' => 317, 'name' => 'Crete'],
            ['id' => 318, 'name' => 'Berkeley'],
            ['id' => 319, 'name' => 'San Rafael'],
            ['id' => 320, 'name' => 'Sioux Center'],
            ['id' => 321, 'name' => 'Oakdale'],
            ['id' => 322, 'name' => 'Durham'],
            ['id' => 323, 'name' => 'Richmond'],
            ['id' => 324, 'name' => 'Ada'],
            ['id' => 325, 'name' => 'Swainsboro'],
            ['id' => 326, 'name' => 'East Stroudsburg'],
            ['id' => 327, 'name' => 'Marshall'],
            ['id' => 328, 'name' => 'Willimantic'],
            ['id' => 329, 'name' => 'Harrisonburg'],
            ['id' => 330, 'name' => 'Ypsilanti'],
            ['id' => 331, 'name' => 'Portales'],
            ['id' => 332, 'name' => 'La Grande'],
            ['id' => 333, 'name' => 'St. Davids'],
            ['id' => 334, 'name' => 'Norfolk'],
            ['id' => 335, 'name' => 'Cheney'],
            ['id' => 336, 'name' => 'Springdale'],
            ['id' => 337, 'name' => 'St. Petersburg'],
            ['id' => 338, 'name' => 'Virginia Beach'],
            ['id' => 339, 'name' => 'Edinboro'],
            ['id' => 340, 'name' => 'Jacksonville'],
            ['id' => 341, 'name' => 'Elizabeth City'],
            ['id' => 342, 'name' => 'Elizabethtown'],
            ['id' => 343, 'name' => 'Elmhurst'],
            ['id' => 344, 'name' => 'Elmira'],
            ['id' => 345, 'name' => 'Elon'],
            ['id' => 346, 'name' => 'Franklin Springs'],
            ['id' => 347, 'name' => 'Emory'],
            ['id' => 348, 'name' => 'Emporia'],
            ['id' => 349, 'name' => 'Beverly'],
            ['id' => 350, 'name' => 'Due West'],
            ['id' => 351, 'name' => 'Eureka'],
            ['id' => 352, 'name' => 'Boca Raton'],
            ['id' => 353, 'name' => 'Fairfield'],
            ['id' => 354, 'name' => 'Teaneck'],
            ['id' => 355, 'name' => 'Fairmont'],
            ['id' => 356, 'name' => 'Ankeny'],
            ['id' => 357, 'name' => 'Farmingdale'],
            ['id' => 358, 'name' => 'Fayetteville'],
            ['id' => 359, 'name' => 'Lodi'],
            ['id' => 360, 'name' => 'Big Rapids'],
            ['id' => 361, 'name' => 'Ferrum'],
            ['id' => 362, 'name' => 'Hancock'],
            ['id' => 363, 'name' => 'Fitchburg'],
            ['id' => 364, 'name' => 'Dix Hills'],
            ['id' => 365, 'name' => 'St. Augustine'],
            ['id' => 366, 'name' => 'Tallahassee'],
            ['id' => 367, 'name' => 'Temple Terrace'],
            ['id' => 368, 'name' => 'Lake City'],
            ['id' => 369, 'name' => 'Fort Myers'],
            ['id' => 370, 'name' => 'Melbourne'],
            ['id' => 371, 'name' => 'Miami Gardens'],
            ['id' => 372, 'name' => 'Hialeah'],
            ['id' => 373, 'name' => 'Lakeland'],
            ['id' => 374, 'name' => 'Hays'],
            ['id' => 375, 'name' => 'Durango'],
            ['id' => 376, 'name' => 'Fort Valley'],
            ['id' => 377, 'name' => 'Framingham'],
            ['id' => 378, 'name' => 'Florence'],
            ['id' => 379, 'name' => 'Baton Rouge'],
            ['id' => 380, 'name' => 'Steubenville'],
            ['id' => 381, 'name' => 'Lancaster'],
            ['id' => 382, 'name' => 'Rindge'],
            ['id' => 383, 'name' => 'Needham'],
            ['id' => 384, 'name' => 'Henderson'],
            ['id' => 385, 'name' => 'Wichita'],
            ['id' => 386, 'name' => 'Frostburg'],
            ['id' => 387, 'name' => 'Erie'],
            ['id' => 388, 'name' => 'Boiling Springs'],
            ['id' => 389, 'name' => 'Scranton'],
            ['id' => 390, 'name' => 'Beaver Falls'],
            ['id' => 391, 'name' => 'Newberg'],
            ['id' => 392, 'name' => 'Fairfax'],
            ['id' => 393, 'name' => 'Georgetown'],
            ['id' => 394, 'name' => 'Milledgeville'],
            ['id' => 395, 'name' => 'Lawrenceville'],
            ['id' => 396, 'name' => 'Statesboro'],
            ['id' => 397, 'name' => 'Americus'],
            ['id' => 398, 'name' => 'Gettysburg'],
            ['id' => 399, 'name' => 'Glenville'],
            ['id' => 400, 'name' => 'Plainfield'],
            ['id' => 401, 'name' => 'Wilmington'],
            ['id' => 402, 'name' => 'Spokane'],
            ['id' => 403, 'name' => 'East Hartford'],
            ['id' => 404, 'name' => 'Wenham'],
            ['id' => 405, 'name' => 'Barnesville'],
            ['id' => 406, 'name' => 'Goshen'],
            ['id' => 407, 'name' => 'Towson'],
            ['id' => 408, 'name' => 'University Park'],
            ['id' => 409, 'name' => 'Wyoming'],
            ['id' => 410, 'name' => 'Winona Lake'],
            ['id' => 411, 'name' => 'Lamoni'],
            ['id' => 412, 'name' => 'Grambling'],
            ['id' => 413, 'name' => 'Allendale'],
            ['id' => 414, 'name' => 'Melrose Park'],
            ['id' => 415, 'name' => 'Elko'],
            ['id' => 416, 'name' => 'Lansing'],
            ['id' => 417, 'name' => 'Poultney'],
            ['id' => 418, 'name' => 'Grinnell'],
            ['id' => 419, 'name' => 'Grove City'],
            ['id' => 420, 'name' => 'Panama City'],
            ['id' => 421, 'name' => 'St. Peter'],
            ['id' => 422, 'name' => 'Gwynedd Valley'],
            ['id' => 423, 'name' => 'Clinton'],
            ['id' => 424, 'name' => 'Hampden-Sydney'],
            ['id' => 425, 'name' => 'Hampton'],
            ['id' => 426, 'name' => 'Hannibal'],
            ['id' => 427, 'name' => 'Searcy'],
            ['id' => 428, 'name' => 'Harrisburg'],
            ['id' => 429, 'name' => 'Oneonta'],
            ['id' => 430, 'name' => 'Hastings'],
            ['id' => 431, 'name' => 'Haverford'],
            ['id' => 432, 'name' => 'Newton Centre'],
            ['id' => 433, 'name' => 'Tiffin'],
            ['id' => 434, 'name' => 'Arkadelphia'],
            ['id' => 435, 'name' => 'Toppenish'],
            ['id' => 436, 'name' => 'High Point'],
            ['id' => 437, 'name' => 'Hamburg'],
            ['id' => 438, 'name' => 'Hillsdale'],
            ['id' => 439, 'name' => 'Hiram'],
            ['id' => 440, 'name' => 'Geneva'],
            ['id' => 441, 'name' => 'Naples'],
            ['id' => 442, 'name' => 'Hempstead'],
            ['id' => 443, 'name' => 'Roanoke'],
            ['id' => 444, 'name' => 'Cromwell'],
            ['id' => 445, 'name' => 'Notre Dame'],
            ['id' => 446, 'name' => 'Oakland'],
            ['id' => 447, 'name' => 'Frederick'],
            ['id' => 448, 'name' => 'Holland'],
            ['id' => 449, 'name' => 'Houghton'],
            ['id' => 450, 'name' => 'Brownwood'],
            ['id' => 451, 'name' => 'Arcata'],
            ['id' => 452, 'name' => 'Stockton'],
            ['id' => 453, 'name' => 'Huntington'],
            ['id' => 454, 'name' => 'Bangor'],
            ['id' => 455, 'name' => 'Pocatello'],
            ['id' => 456, 'name' => 'Bloomington'],
            ['id' => 457, 'name' => 'Immaculata'],
            ['id' => 458, 'name' => 'Fort Pierce'],
            ['id' => 459, 'name' => 'Fort Wayne'],
            ['id' => 460, 'name' => 'Terre Haute'],
            ['id' => 461, 'name' => 'Kokomo'],
            ['id' => 462, 'name' => 'Gary'],
            ['id' => 463, 'name' => 'Indiana'],
            ['id' => 464, 'name' => 'South Bend'],
            ['id' => 465, 'name' => 'New Albany'],
            ['id' => 466, 'name' => 'Marion'],
            ['id' => 467, 'name' => 'New Rochelle'],
            ['id' => 468, 'name' => 'Ames'],
            ['id' => 469, 'name' => 'Duarte'],
            ['id' => 470, 'name' => 'Jamestown'],
            ['id' => 471, 'name' => 'Hawkins'],
            ['id' => 472, 'name' => 'Siloam Springs'],
            ['id' => 473, 'name' => 'University Heights'],
            ['id' => 474, 'name' => 'Pleasant Hill'],
            ['id' => 475, 'name' => 'Escondido'],
            ['id' => 476, 'name' => 'Charlotte'],
            ['id' => 477, 'name' => 'Johnson'],
            ['id' => 478, 'name' => 'Knoxville'],
            ['id' => 479, 'name' => 'Elgin'],
            ['id' => 480, 'name' => 'Huntingdon'],
            ['id' => 481, 'name' => 'Kalamazoo'],
            ['id' => 482, 'name' => 'Manhattan'],
            ['id' => 483, 'name' => 'Davenport'],
            ['id' => 484, 'name' => 'Union'],
            ['id' => 485, 'name' => 'Kennesaw'],
            ['id' => 486, 'name' => 'Kent'],
            ['id' => 487, 'name' => 'Grayson'],
            ['id' => 488, 'name' => 'Frankfort'],
            ['id' => 489, 'name' => 'Gambier'],
            ['id' => 490, 'name' => 'Kettering'],
            ['id' => 491, 'name' => 'Keuka Park'],
            ['id' => 492, 'name' => 'La Plume'],
            ['id' => 493, 'name' => 'Bristol'],
            ['id' => 494, 'name' => 'Wilkes-Barre'],
            ['id' => 495, 'name' => 'Galesburg'],
            ['id' => 496, 'name' => 'Kutztown'],
            ['id' => 497, 'name' => 'Easton'],
            ['id' => 498, 'name' => 'LaGrange'],
            ['id' => 499, 'name' => 'Laguna Beach'],
            ['id' => 500, 'name' => 'Painesville'],
            ['id' => 501, 'name' => 'Lake Forest'],
            ['id' => 502, 'name' => 'Sault Ste. Marie'],
            ['id' => 503, 'name' => 'Kirkland'],
            ['id' => 504, 'name' => 'Plymouth'],
            ['id' => 505, 'name' => 'Beaumont'],
            ['id' => 506, 'name' => 'Greenwood'],
            ['id' => 507, 'name' => 'Putney'],
            ['id' => 508, 'name' => 'Langston'],
            ['id' => 509, 'name' => 'Newton'],
            ['id' => 510, 'name' => 'Southfield'],
            ['id' => 511, 'name' => 'Appleton'],
            ['id' => 512, 'name' => 'Syracuse'],
            ['id' => 513, 'name' => 'Annville'],
            ['id' => 514, 'name' => 'Banner Elk'],
            ['id' => 515, 'name' => 'Bethlehem'],
            ['id' => 516, 'name' => 'Hickory'],
            ['id' => 517, 'name' => 'Longview'],
            ['id' => 518, 'name' => 'Romeoville'],
            ['id' => 519, 'name' => 'Lynchburg'],
            ['id' => 520, 'name' => 'San Dimas'],
            ['id' => 521, 'name' => 'Marietta'],
            ['id' => 522, 'name' => 'Gaffney'],
            ['id' => 523, 'name' => 'Southington'],
            ['id' => 524, 'name' => 'Harrogate'],
            ['id' => 525, 'name' => 'Lincoln University'],
            ['id' => 526, 'name' => 'St. Charles'],
            ['id' => 527, 'name' => 'McMinnville'],
            ['id' => 528, 'name' => 'Lock Haven'],
            ['id' => 529, 'name' => 'Chesterfield'],
            ['id' => 530, 'name' => 'Loma Linda'],
            ['id' => 531, 'name' => 'Farmville'],
            ['id' => 532, 'name' => 'Alexandria'],
            ['id' => 533, 'name' => 'Ruston'],
            ['id' => 534, 'name' => 'Sylvania'],
            ['id' => 535, 'name' => 'Lubbock'],
            ['id' => 536, 'name' => 'Decorah'],
            ['id' => 537, 'name' => 'Williamsport'],
            ['id' => 538, 'name' => 'Lyndonville'],
            ['id' => 539, 'name' => 'Batesville'],
            ['id' => 540, 'name' => 'Livonia'],
            ['id' => 541, 'name' => 'Castine'],
            ['id' => 542, 'name' => 'North Manchester'],
            ['id' => 543, 'name' => 'Riverdale'],
            ['id' => 544, 'name' => 'Purchase'],
            ['id' => 545, 'name' => 'Mansfield'],
            ['id' => 546, 'name' => 'Watertown'],
            ['id' => 547, 'name' => 'Fond du Lac'],
            ['id' => 548, 'name' => 'Poughkeepsie'],
            ['id' => 549, 'name' => 'Marlboro'],
            ['id' => 550, 'name' => 'Mars Hill'],
            ['id' => 551, 'name' => 'New Ulm'],
            ['id' => 552, 'name' => 'Pulaski'],
            ['id' => 553, 'name' => 'Staunton'],
            ['id' => 554, 'name' => 'Marylhurst'],
            ['id' => 555, 'name' => 'Rancho Palos Verdes'],
            ['id' => 556, 'name' => 'Maryville'],
            ['id' => 557, 'name' => 'North Adams'],
            ['id' => 558, 'name' => 'Buzzards Bay'],
            ['id' => 559, 'name' => 'Andover'],
            ['id' => 560, 'name' => 'Mayville'],
            ['id' => 561, 'name' => 'Westminster'],
            ['id' => 562, 'name' => 'Lake Charles'],
            ['id' => 563, 'name' => 'Atherton'],
            ['id' => 564, 'name' => 'Macon'],
            ['id' => 565, 'name' => 'Dobbs Ferry'],
            ['id' => 566, 'name' => 'Toledo'],
            ['id' => 567, 'name' => 'Raleigh'],
            ['id' => 568, 'name' => 'North Andover'],
            ['id' => 569, 'name' => 'Mechanicsburg'],
            ['id' => 570, 'name' => 'Oxford'],
            ['id' => 571, 'name' => 'Farmington Hills'],
            ['id' => 572, 'name' => 'East Lansing'],
            ['id' => 573, 'name' => 'Oklahoma City'],
            ['id' => 574, 'name' => 'Olathe'],
            ['id' => 575, 'name' => 'Middlebury'],
            ['id' => 576, 'name' => 'Midland'],
            ['id' => 577, 'name' => 'Fremont'],
            ['id' => 578, 'name' => 'Midway'],
            ['id' => 579, 'name' => 'Wichita Falls'],
            ['id' => 580, 'name' => 'Downers Grove'],
            ['id' => 581, 'name' => 'Millersville'],
            ['id' => 582, 'name' => 'Elizabethton'],
            ['id' => 583, 'name' => 'Minot'],
            ['id' => 584, 'name' => 'Mississippi State'],
            ['id' => 585, 'name' => 'Itta Bena'],
            ['id' => 586, 'name' => 'Joplin'],
            ['id' => 587, 'name' => 'Rolla'],
            ['id' => 588, 'name' => 'Rockville Centre'],
            ['id' => 589, 'name' => 'Monmouth'],
            ['id' => 590, 'name' => 'West Long Branch'],
            ['id' => 591, 'name' => 'Bronx'],
            ['id' => 592, 'name' => 'Bozeman'],
            ['id' => 593, 'name' => 'Billings'],
            ['id' => 594, 'name' => 'Havre'],
            ['id' => 595, 'name' => 'Butte'],
            ['id' => 596, 'name' => 'Montclair'],
            ['id' => 597, 'name' => 'Montreat'],
            ['id' => 598, 'name' => 'Morehead'],
            ['id' => 599, 'name' => 'Sumter'],
            ['id' => 600, 'name' => 'Morrisville'],
            ['id' => 601, 'name' => 'Cresson'],
            ['id' => 602, 'name' => 'South Hadley'],
            ['id' => 603, 'name' => 'Yankton'],
            ['id' => 604, 'name' => 'Newburgh'],
            ['id' => 605, 'name' => 'Emmitsburg'],
            ['id' => 606, 'name' => 'Murray'],
            ['id' => 607, 'name' => 'New Concord'],
            ['id' => 608, 'name' => 'Boulder'],
            ['id' => 609, 'name' => 'Rapid City'],
            ['id' => 610, 'name' => 'Fort Lesley J McNair'],
            ['id' => 611, 'name' => 'Silver Spring'],
            ['id' => 612, 'name' => 'La Jolla'],
            ['id' => 613, 'name' => 'Lombard'],
            ['id' => 614, 'name' => 'Monterey'],
            ['id' => 615, 'name' => 'Papillion'],
            ['id' => 616, 'name' => 'Aston'],
            ['id' => 617, 'name' => 'Salt Lake City'],
            ['id' => 618, 'name' => 'Sarasota'],
            ['id' => 619, 'name' => 'Henniker'],
            ['id' => 620, 'name' => 'East Greenwich'],
            ['id' => 621, 'name' => 'Eugene'],
            ['id' => 622, 'name' => 'Jersey City'],
            ['id' => 623, 'name' => 'Newark'],
            ['id' => 624, 'name' => 'Socorro'],
            ['id' => 625, 'name' => 'Las Cruces'],
            ['id' => 626, 'name' => 'Old Westbury'],
            ['id' => 627, 'name' => 'Valhalla'],
            ['id' => 628, 'name' => 'Newberry'],
            ['id' => 629, 'name' => 'Niagara University'],
            ['id' => 630, 'name' => 'Thibodaux'],
            ['id' => 631, 'name' => 'Dudley'],
            ['id' => 632, 'name' => 'Rocky Mount'],
            ['id' => 633, 'name' => 'Naperville'],
            ['id' => 634, 'name' => 'Fargo'],
            ['id' => 635, 'name' => 'Tigerville'],
            ['id' => 636, 'name' => 'Warner'],
            ['id' => 637, 'name' => 'Rootstown'],
            ['id' => 638, 'name' => 'Tahlequah'],
            ['id' => 639, 'name' => 'Flagstaff'],
            ['id' => 640, 'name' => 'DeKalb'],
            ['id' => 641, 'name' => 'Highland Heights'],
            ['id' => 642, 'name' => 'Marquette'],
            ['id' => 643, 'name' => 'Espanola'],
            ['id' => 644, 'name' => 'Aberdeen'],
            ['id' => 645, 'name' => 'Haverhill'],
            ['id' => 646, 'name' => 'Niceville'],
            ['id' => 647, 'name' => 'Nampa'],
            ['id' => 648, 'name' => 'Orange City'],
            ['id' => 649, 'name' => 'Alva'],
            ['id' => 650, 'name' => 'Natchitoches'],
            ['id' => 651, 'name' => 'Evanston'],
            ['id' => 652, 'name' => 'Nyack'],
            ['id' => 653, 'name' => 'Oakland City'],
            ['id' => 654, 'name' => 'Rochester Hills'],
            ['id' => 655, 'name' => 'Huntsville'],
            ['id' => 656, 'name' => 'Oberlin'],
            ['id' => 657, 'name' => 'Circleville'],
            ['id' => 658, 'name' => 'Ironton'],
            ['id' => 659, 'name' => 'Chillicothe'],
            ['id' => 660, 'name' => 'Vienna'],
            ['id' => 661, 'name' => 'Delaware'],
            ['id' => 662, 'name' => 'Shawnee'],
            ['id' => 663, 'name' => 'Edmond'],
            ['id' => 664, 'name' => 'Goodwell'],
            ['id' => 665, 'name' => 'Stillwater'],
            ['id' => 666, 'name' => 'Bartlesville'],
            ['id' => 667, 'name' => 'Olivet'],
            ['id' => 668, 'name' => 'Bourbonnais'],
            ['id' => 669, 'name' => 'Tulsa'],
            ['id' => 670, 'name' => 'Klamath Falls'],
            ['id' => 671, 'name' => 'Corvallis'],
            ['id' => 672, 'name' => 'Ottawa'],
            ['id' => 673, 'name' => 'Westerville'],
            ['id' => 674, 'name' => 'Tacoma'],
            ['id' => 675, 'name' => 'Angwin'],
            ['id' => 676, 'name' => 'Forest Grove'],
            ['id' => 677, 'name' => 'Carpinteria'],
            ['id' => 678, 'name' => 'West Palm Beach'],
            ['id' => 679, 'name' => 'Lake Worth'],
            ['id' => 680, 'name' => 'Palo Alto'],
            ['id' => 681, 'name' => 'Santa Monica'],
            ['id' => 682, 'name' => 'Parkville'],
            ['id' => 683, 'name' => 'Paul Smiths'],
            ['id' => 684, 'name' => 'Hershey'],
            ['id' => 685, 'name' => 'Pensacola'],
            ['id' => 686, 'name' => 'Malibu'],
            ['id' => 687, 'name' => 'Peru'],
            ['id' => 688, 'name' => 'Misenheimer'],
            ['id' => 689, 'name' => 'Chatsworth'],
            ['id' => 690, 'name' => 'Demorest'],
            ['id' => 691, 'name' => 'Winston Salem'],
            ['id' => 692, 'name' => 'Pittsburg'],
            ['id' => 693, 'name' => 'West Point'],
            ['id' => 694, 'name' => 'Winter Haven'],
            ['id' => 695, 'name' => 'Waterbury'],
            ['id' => 696, 'name' => 'Prairie View'],
            ['id' => 697, 'name' => 'Prescott'],
            ['id' => 698, 'name' => 'Princeton'],
            ['id' => 699, 'name' => 'Elsah'],
            ['id' => 700, 'name' => 'West Lafayette'],
            ['id' => 701, 'name' => 'Hammond'],
            ['id' => 702, 'name' => 'Flushing'],
            ['id' => 703, 'name' => 'Hamden'],
            ['id' => 704, 'name' => 'Radford'],
            ['id' => 705, 'name' => 'Mahwah'],
            ['id' => 706, 'name' => 'St. Cloud'],
            ['id' => 707, 'name' => 'Weston'],
            ['id' => 708, 'name' => 'Waleska'],
            ['id' => 709, 'name' => 'Troy'],
            ['id' => 710, 'name' => 'Chattanooga'],
            ['id' => 711, 'name' => 'Ripon'],
            ['id' => 712, 'name' => 'Nashua'],
            ['id' => 713, 'name' => 'Moon Township'],
            ['id' => 714, 'name' => 'Rockford'],
            ['id' => 715, 'name' => 'Parker'],
            ['id' => 716, 'name' => 'Claremore'],
            ['id' => 717, 'name' => 'Winter Park'],
            ['id' => 718, 'name' => 'North Chicago'],
            ['id' => 719, 'name' => 'Rosemont'],
            ['id' => 720, 'name' => 'Glassboro'],
            ['id' => 721, 'name' => 'Holly Springs'],
            ['id' => 722, 'name' => 'New Brunswick'],
            ['id' => 723, 'name' => 'University Center'],
            ['id' => 724, 'name' => 'Manchester'],
            ['id' => 725, 'name' => 'Loretto'],
            ['id' => 726, 'name' => 'Palatka'],
            ['id' => 727, 'name' => 'Rensselaer'],
            ['id' => 728, 'name' => 'Standish'],
            ['id' => 729, 'name' => 'Saint Leo'],
            ['id' => 730, 'name' => 'Lacey'],
            ['id' => 731, 'name' => 'Saint Mary of the Woods'],
            ['id' => 732, 'name' => 'Moraga'],
            ['id' => 733, 'name' => 'Winona'],
            ['id' => 734, 'name' => 'Colchester'],
            ['id' => 735, 'name' => 'Latrobe'],
            ['id' => 736, 'name' => 'Elkins Park'],
            ['id' => 737, 'name' => 'Newport'],
            ['id' => 738, 'name' => 'Santee'],
            ['id' => 739, 'name' => 'Clovis'],
            ['id' => 740, 'name' => 'San José'],
            ['id' => 741, 'name' => 'Santa Clara'],
            ['id' => 742, 'name' => 'Santa Fe'],
            ['id' => 743, 'name' => 'Largo'],
            ['id' => 744, 'name' => 'Kerrville'],
            ['id' => 745, 'name' => 'Sanford'],
            ['id' => 746, 'name' => 'South Orange'],
            ['id' => 747, 'name' => 'Greensburg'],
            ['id' => 748, 'name' => 'Sewanee'],
            ['id' => 749, 'name' => 'Portsmouth'],
            ['id' => 750, 'name' => 'Winchester'],
            ['id' => 751, 'name' => 'Shepherdstown'],
            ['id' => 752, 'name' => 'Shippensburg'],
            ['id' => 753, 'name' => 'Rome'],
            ['id' => 754, 'name' => 'Loudonville'],
            ['id' => 755, 'name' => 'Incline Village'],
            ['id' => 756, 'name' => 'Manitowoc'],
            ['id' => 757, 'name' => 'Indianola'],
            ['id' => 758, 'name' => 'Redding'],
            ['id' => 759, 'name' => 'Brattleboro'],
            ['id' => 760, 'name' => 'Saratoga Springs'],
            ['id' => 761, 'name' => 'Slippery Rock'],
            ['id' => 762, 'name' => 'Northampton'],
            ['id' => 763, 'name' => 'Ephraim'],
            ['id' => 764, 'name' => 'Aliso Viejo'],
            ['id' => 765, 'name' => 'Rohnert Park'],
            ['id' => 766, 'name' => 'Brookings'],
            ['id' => 767, 'name' => 'Douglas'],
            ['id' => 768, 'name' => 'McAllen'],
            ['id' => 769, 'name' => 'Cape Girardeau'],
            ['id' => 770, 'name' => 'Durant'],
            ['id' => 771, 'name' => 'Collegedale'],
            ['id' => 772, 'name' => 'Magnolia'],
            ['id' => 773, 'name' => 'Carbondale'],
            ['id' => 774, 'name' => 'Edwardsville'],
            ['id' => 775, 'name' => 'Cedar City'],
            ['id' => 776, 'name' => 'Buena Vista'],
            ['id' => 777, 'name' => 'Central'],
            ['id' => 778, 'name' => 'Bolivar'],
            ['id' => 779, 'name' => 'Tucson'],
            ['id' => 780, 'name' => 'Waxahachie'],
            ['id' => 781, 'name' => 'Winfield'],
            ['id' => 782, 'name' => 'Weatherford'],
            ['id' => 783, 'name' => 'Spring Arbor'],
            ['id' => 784, 'name' => 'Mobile'],
            ['id' => 785, 'name' => 'Laurinburg'],
            ['id' => 786, 'name' => 'Annapolis'],
            ['id' => 787, 'name' => 'Clearwater'],
            ['id' => 788, 'name' => 'St. Bonaventure'],
            ['id' => 789, 'name' => 'Brooklyn Heights'],
            ['id' => 790, 'name' => 'Queens'],
            ['id' => 791, 'name' => 'Florissant'],
            ['id' => 792, 'name' => 'St. Mary\'s City'],
            ['id' => 793, 'name' => 'De Pere'],
            ['id' => 794, 'name' => 'Sparkill'],
            ['id' => 795, 'name' => 'Bridgeport'],
            ['id' => 796, 'name' => 'Stanford'],
            ['id' => 797, 'name' => 'Bradenton'],
            ['id' => 798, 'name' => 'Fredonia'],
            ['id' => 799, 'name' => 'New Paltz'],
            ['id' => 800, 'name' => 'Oswego'],
            ['id' => 801, 'name' => 'Plattsburgh'],
            ['id' => 802, 'name' => 'Nacogdoches'],
            ['id' => 803, 'name' => 'Sterling'],
            ['id' => 804, 'name' => 'Craftsbury Common'],
            ['id' => 805, 'name' => 'DeLand'],
            ['id' => 806, 'name' => 'Hoboken'],
            ['id' => 807, 'name' => 'Stevenson'],
            ['id' => 808, 'name' => 'Tuscaloosa'],
            ['id' => 809, 'name' => 'Galloway'],
            ['id' => 810, 'name' => 'Stony Brook'],
            ['id' => 811, 'name' => 'Alpine'],
            ['id' => 812, 'name' => 'Cobleskill'],
            ['id' => 813, 'name' => 'Cortland'],
            ['id' => 814, 'name' => 'Delhi'],
            ['id' => 815, 'name' => 'Geneseo'],
            ['id' => 816, 'name' => 'Throggs Neck'],
            ['id' => 817, 'name' => 'Utica'],
            ['id' => 818, 'name' => 'Selinsgrove'],
            ['id' => 819, 'name' => 'Swarthmore'],
            ['id' => 820, 'name' => 'Sweet Briar'],
            ['id' => 821, 'name' => 'Hillsboro'],
            ['id' => 822, 'name' => 'Talladega'],
            ['id' => 823, 'name' => 'Stephenville'],
            ['id' => 824, 'name' => 'Upland'],
            ['id' => 825, 'name' => 'Cookeville'],
            ['id' => 826, 'name' => 'Laredo'],
            ['id' => 827, 'name' => 'College Station'],
            ['id' => 828, 'name' => 'Galveston'],
            ['id' => 829, 'name' => 'Commerce'],
            ['id' => 830, 'name' => 'Corpus Christi'],
            ['id' => 831, 'name' => 'Kingsville'],
            ['id' => 832, 'name' => 'Texarkana'],
            ['id' => 833, 'name' => 'Fort Worth'],
            ['id' => 834, 'name' => 'Tyler'],
            ['id' => 835, 'name' => 'Seguin'],
            ['id' => 836, 'name' => 'Denton'],
            ['id' => 837, 'name' => 'Graceville'],
            ['id' => 838, 'name' => 'Brockport'],
            ['id' => 839, 'name' => 'Ewing'],
            ['id' => 840, 'name' => 'Duluth'],
            ['id' => 841, 'name' => 'White Plains'],
            ['id' => 842, 'name' => 'Wooster'],
            ['id' => 843, 'name' => 'Hyde Park'],
            ['id' => 844, 'name' => 'Olympia'],
            ['id' => 845, 'name' => 'Southlake'],
            ['id' => 846, 'name' => 'Santa Clarita'],
            ['id' => 847, 'name' => 'Falmouth'],
            ['id' => 848, 'name' => 'Scottsdale'],
            ['id' => 849, 'name' => 'Findlay'],
            ['id' => 850, 'name' => 'Orono'],
            ['id' => 851, 'name' => 'Missoula'],
            ['id' => 852, 'name' => 'Dillon'],
            ['id' => 853, 'name' => 'Norman'],
            ['id' => 854, 'name' => 'Tampa'],
            ['id' => 855, 'name' => 'Martin'],
            ['id' => 856, 'name' => 'Richardson'],
            ['id' => 857, 'name' => 'El Paso'],
            ['id' => 858, 'name' => 'Odessa'],
            ['id' => 859, 'name' => 'Wise'],
            ['id' => 860, 'name' => 'Inglewood'],
            ['id' => 861, 'name' => 'Santa Paula'],
            ['id' => 862, 'name' => 'Trenton'],
            ['id' => 863, 'name' => 'Crestview Hills'],
            ['id' => 864, 'name' => 'Merrimack'],
            ['id' => 865, 'name' => 'Thomasville'],
            ['id' => 866, 'name' => 'Toccoa Falls'],
            ['id' => 867, 'name' => 'Tougaloo'],
            ['id' => 868, 'name' => 'Lexington'],
            ['id' => 869, 'name' => 'Angola'],
            ['id' => 870, 'name' => 'Ellendale'],
            ['id' => 871, 'name' => 'Palos Heights'],
            ['id' => 872, 'name' => 'Hartford'],
            ['id' => 873, 'name' => 'Trinity'],
            ['id' => 874, 'name' => 'Deerfield'],
            ['id' => 875, 'name' => 'South Point'],
            ['id' => 876, 'name' => 'Medford'],
            ['id' => 877, 'name' => 'Greeneville'],
            ['id' => 878, 'name' => 'Tuskegee'],
            ['id' => 879, 'name' => 'Bethesda'],
            ['id' => 880, 'name' => 'Schenectady'],
            ['id' => 881, 'name' => 'Barbourville'],
            ['id' => 882, 'name' => 'Kings Point'],
            ['id' => 883, 'name' => 'Daphne'],
            ['id' => 884, 'name' => 'Unity'],
            ['id' => 885, 'name' => 'Akron'],
            ['id' => 886, 'name' => 'Fairbanks'],
            ['id' => 887, 'name' => 'Juneau'],
            ['id' => 888, 'name' => 'Fort Smith'],
            ['id' => 889, 'name' => 'Monticello'],
            ['id' => 890, 'name' => 'Pine Bluff'],
            ['id' => 891, 'name' => 'Davis'],
            ['id' => 892, 'name' => 'Merced'],
            ['id' => 893, 'name' => 'Santa Cruz'],
            ['id' => 894, 'name' => 'Warrensburg'],
            ['id' => 895, 'name' => 'Storrs'],
            ['id' => 896, 'name' => 'Irving'],
            ['id' => 897, 'name' => 'Evansville'],
            ['id' => 898, 'name' => 'West Hartford'],
            ['id' => 899, 'name' => 'Hilo'],
            ['id' => 900, 'name' => 'Kapolei'],
            ['id' => 901, 'name' => 'Victoria'],
            ['id' => 902, 'name' => 'Moscow'],
            ['id' => 903, 'name' => 'Champaign'],
            ['id' => 904, 'name' => 'Iowa City'],
            ['id' => 905, 'name' => 'Lawrence'],
            ['id' => 906, 'name' => 'La Verne'],
            ['id' => 907, 'name' => 'Lafayette'],
            ['id' => 908, 'name' => 'Monroe'],
            ['id' => 909, 'name' => 'Farmington'],
            ['id' => 910, 'name' => 'Fort Kent'],
            ['id' => 911, 'name' => 'Machias'],
            ['id' => 912, 'name' => 'Presque Isle'],
            ['id' => 913, 'name' => 'Belton'],
            ['id' => 914, 'name' => 'Fredericksburg'],
            ['id' => 915, 'name' => 'College Park'],
            ['id' => 916, 'name' => 'Princess Anne'],
            ['id' => 917, 'name' => 'Adelphi'],
            ['id' => 918, 'name' => 'North Dartmouth'],
            ['id' => 919, 'name' => 'Lowell'],
            ['id' => 920, 'name' => 'Coral Gables'],
            ['id' => 921, 'name' => 'Dearborn'],
            ['id' => 922, 'name' => 'University'],
            ['id' => 923, 'name' => 'Montevallo'],
            ['id' => 924, 'name' => 'Mount Olive'],
            ['id' => 925, 'name' => 'Alliance'],
            ['id' => 926, 'name' => 'Kearney'],
            ['id' => 927, 'name' => 'Reno'],
            ['id' => 928, 'name' => 'Biddeford'],
            ['id' => 929, 'name' => 'West Haven'],
            ['id' => 930, 'name' => 'Albuquerque'],
            ['id' => 931, 'name' => 'Asheville'],
            ['id' => 932, 'name' => 'Chapel Hill'],
            ['id' => 933, 'name' => 'Pembroke'],
            ['id' => 934, 'name' => 'Grand Forks'],
            ['id' => 935, 'name' => 'Dahlonega'],
            ['id' => 936, 'name' => 'Greeley'],
            ['id' => 937, 'name' => 'Cedar Falls'],
            ['id' => 938, 'name' => 'Lima'],
            ['id' => 939, 'name' => 'Pikeville'],
            ['id' => 940, 'name' => 'Great Falls'],
            ['id' => 941, 'name' => 'Redlands'],
            ['id' => 942, 'name' => 'Kingston'],
            ['id' => 943, 'name' => 'Rio Grande'],
            ['id' => 944, 'name' => 'Leavenworth'],
            ['id' => 945, 'name' => 'Chickasha'],
            ['id' => 946, 'name' => 'Aiken'],
            ['id' => 947, 'name' => 'Vermillion'],
            ['id' => 948, 'name' => 'Hattiesburg'],
            ['id' => 949, 'name' => 'Joliet'],
            ['id' => 950, 'name' => 'Brownsville'],
            ['id' => 951, 'name' => 'Hobbs'],
            ['id' => 952, 'name' => 'Rosemead'],
            ['id' => 953, 'name' => 'Phoenixville'],
            ['id' => 954, 'name' => 'Charlottesville'],
            ['id' => 955, 'name' => 'Livingston'],
            ['id' => 956, 'name' => 'Carrollton'],
            ['id' => 957, 'name' => 'Eau Claire'],
            ['id' => 958, 'name' => 'La Crosse'],
            ['id' => 959, 'name' => 'Oshkosh'],
            ['id' => 960, 'name' => 'Platteville'],
            ['id' => 961, 'name' => 'River Falls'],
            ['id' => 962, 'name' => 'Stevens Point'],
            ['id' => 963, 'name' => 'Menomonie'],
            ['id' => 964, 'name' => 'Superior'],
            ['id' => 965, 'name' => 'Whitewater'],
            ['id' => 966, 'name' => 'Laramie'],
            ['id' => 967, 'name' => 'Urbana'],
            ['id' => 968, 'name' => 'Collegeville'],
            ['id' => 969, 'name' => 'Pepper Pike'],
            ['id' => 970, 'name' => 'Logan'],
            ['id' => 971, 'name' => 'Orem'],
            ['id' => 972, 'name' => 'Valdosta'],
            ['id' => 973, 'name' => 'Valley City'],
            ['id' => 974, 'name' => 'Valparaíso'],
            ['id' => 975, 'name' => 'Costa Mesa'],
            ['id' => 976, 'name' => 'Montpelier'],
            ['id' => 977, 'name' => 'South Royalton'],
            ['id' => 978, 'name' => 'Randolph Center'],
            ['id' => 979, 'name' => 'Villanova'],
            ['id' => 980, 'name' => 'Vincennes'],
            ['id' => 981, 'name' => 'Blacksburg'],
            ['id' => 982, 'name' => 'Petersburg'],
            ['id' => 983, 'name' => 'Denmark'],
            ['id' => 984, 'name' => 'Crawfordsville'],
            ['id' => 985, 'name' => 'Forest City'],
            ['id' => 986, 'name' => 'College Place'],
            ['id' => 987, 'name' => 'North Canton'],
            ['id' => 988, 'name' => 'Lake Wales'],
            ['id' => 989, 'name' => 'Swannanoa'],
            ['id' => 990, 'name' => 'Waverly'],
            ['id' => 991, 'name' => 'Topeka'],
            ['id' => 992, 'name' => 'Takoma Park'],
            ['id' => 993, 'name' => 'Chestertown'],
            ['id' => 994, 'name' => 'Pullman'],
            ['id' => 995, 'name' => 'Plainview'],
            ['id' => 996, 'name' => 'Wayne'],
            ['id' => 997, 'name' => 'Waynesburg'],
            ['id' => 998, 'name' => 'Glen Cove'],
            ['id' => 999, 'name' => 'Ogden'],
            ['id' => 1000, 'name' => 'Wellesley'],
            ['id' => 1001, 'name' => 'Middletown'],
            ['id' => 1002, 'name' => 'West Chester'],
            ['id' => 1003, 'name' => 'North Hollywood'],
            ['id' => 1004, 'name' => 'West Liberty'],
            ['id' => 1005, 'name' => 'Canyon'],
            ['id' => 1006, 'name' => 'Institute'],
            ['id' => 1007, 'name' => 'Morgantown'],
            ['id' => 1008, 'name' => 'Parkersburg'],
            ['id' => 1009, 'name' => 'Buckhannon'],
            ['id' => 1010, 'name' => 'Cullowhee'],
            ['id' => 1011, 'name' => 'Danbury'],
            ['id' => 1012, 'name' => 'Macomb'],
            ['id' => 1013, 'name' => 'Carson City'],
            ['id' => 1014, 'name' => 'Silver City'],
            ['id' => 1015, 'name' => 'Gunnison'],
            ['id' => 1016, 'name' => 'Bellingham'],
            ['id' => 1017, 'name' => 'Westfield'],
            ['id' => 1018, 'name' => 'Fulton'],
            ['id' => 1019, 'name' => 'New Wilmington'],
            ['id' => 1020, 'name' => 'Wheaton'],
            ['id' => 1021, 'name' => 'Norton'],
            ['id' => 1022, 'name' => 'Wheeling'],
            ['id' => 1023, 'name' => 'Walla Walla'],
            ['id' => 1024, 'name' => 'Whittier'],
            ['id' => 1025, 'name' => 'Chester'],
            ['id' => 1026, 'name' => 'Rocklin'],
            ['id' => 1027, 'name' => 'Liberty'],
            ['id' => 1028, 'name' => 'Oskaloosa'],
            ['id' => 1029, 'name' => 'Walnut Ridge'],
            ['id' => 1030, 'name' => 'Williamstown'],
            ['id' => 1031, 'name' => 'New Castle'],
            ['id' => 1032, 'name' => 'Chambersburg'],
            ['id' => 1033, 'name' => 'Wingate'],
            ['id' => 1034, 'name' => 'Rock Hill'],
            ['id' => 1035, 'name' => 'Burbank'],
            ['id' => 1036, 'name' => 'York'],
            ['id' => 1037, 'name' => 'Jamaica'],
            ['id' => 1038, 'name' => 'Young Harris'],
            ['id' => 1039, 'name' => 'Youngstown'],
        ];
    }
}
