<?php

use common\src\migration\TableMigration;

/**
 * Class m190409_033529_table_create_area
 */
class m190409_033529_create_table_area extends TableMigration
{
    /**
     * @inheritDoc
     */
    protected function getTableName(): string
    {
        return 'area';
    }

    /**
     * @inheritDoc
     */
    protected function getTableColumns(): array
    {
        return [
            'id' => $this->primaryKey(),
            'name' => $this->string()->notNull(),
            'state_id' => $this->integer()->notNull(),
        ];
    }

    /**
     * @inheritDoc
     */
    protected function getForeignKeysParams(): array
    {
        return [
            ['area_state_fk', 'area', 'state_id', 'state', 'id']
        ];
    }

    /**
     * @inheritDoc
     */
    protected function getTableColumnValues(): array
    {
        return [
            ['id' => 1, 'state_id' => 1, 'name' => 'Anniston-Oxford-Jacksonville AL Metro'],
            ['id' => 2, 'state_id' => 1, 'name' => 'Auburn-Opelika AL Metro'],
            ['id' => 3, 'state_id' => 1, 'name' => 'Birmingham-Hoover AL Metro'],
            ['id' => 4, 'state_id' => 1, 'name' => 'Decatur AL Metro'],
            ['id' => 5, 'state_id' => 1, 'name' => 'Dothan AL Metro'],
            ['id' => 6, 'state_id' => 1, 'name' => 'Florence-Muscle Shoals AL Metro'],
            ['id' => 7, 'state_id' => 1, 'name' => 'Huntsville AL Metro'],
            ['id' => 8, 'state_id' => 1, 'name' => 'Mobile AL Metro'],
            ['id' => 9, 'state_id' => 1, 'name' => 'Montgomery AL Metro'],
            ['id' => 10, 'state_id' => 2, 'name' => 'Anchorage AK Metro'],
            ['id' => 11, 'state_id' => 2, 'name' => 'Fairbanks AK Metro'],
            ['id' => 12, 'state_id' => 2, 'name' => 'Juneau AK Micro'],
            ['id' => 13, 'state_id' => 2, 'name' => 'NonMetro US'],
            ['id' => 14, 'state_id' => 3, 'name' => 'Flagstaff AZ Metro'],
            ['id' => 15, 'state_id' => 3, 'name' => 'Lake Havasu City-Kingman AZ Metro'],
            ['id' => 16, 'state_id' => 3, 'name' => 'Phoenix-Mesa-Scottsdale AZ Metro'],
            ['id' => 17, 'state_id' => 3, 'name' => 'Sierra Vista-Douglas AZ Metro'],
            ['id' => 18, 'state_id' => 3, 'name' => 'Tucson AZ Metro'],
            ['id' => 19, 'state_id' => 3, 'name' => 'Yuma AZ Metro'],
            ['id' => 20, 'state_id' => 4, 'name' => 'Fayetteville-Springdale-Rogers AR-MO Metro'],
            ['id' => 21, 'state_id' => 4, 'name' => 'Hot Springs AR Metro'],
            ['id' => 22, 'state_id' => 4, 'name' => 'Jonesboro AR Metro'],
            ['id' => 23, 'state_id' => 4, 'name' => 'Little Rock-North Little Rock-Conway AR Metro'],
            ['id' => 24, 'state_id' => 5, 'name' => 'Anaheim-Santa Ana-Irvine CA Metro Div.'],
            ['id' => 25, 'state_id' => 5, 'name' => 'Bakersfield CA Metro'],
            ['id' => 26, 'state_id' => 5, 'name' => 'Los Angeles-Long Beach-Glendale CA Metro Div.'],
            ['id' => 27, 'state_id' => 5, 'name' => 'Oakland-Hayward-Berkeley CA Metro Div.'],
            ['id' => 28, 'state_id' => 5, 'name' => 'Sacramento-Roseville-Arden-Arcade CA Metro'],
            ['id' => 29, 'state_id' => 5, 'name' => 'San Diego-Carlsbad CA Metro'],
            ['id' => 30, 'state_id' => 5, 'name' => 'San Francisco-Redwood City-South San Francisco CA Metro Div.'],
            ['id' => 31, 'state_id' => 5, 'name' => 'Stockton-Lodi CA Metro'],
            ['id' => 32, 'state_id' => 6, 'name' => 'Colorado Springs CO Metro'],
            ['id' => 33, 'state_id' => 6, 'name' => 'Denver-Aurora-Lakewood CO Metro'],
            ['id' => 34, 'state_id' => 6, 'name' => 'Grand Junction CO Metro'],
            ['id' => 35, 'state_id' => 6, 'name' => 'Pueblo CO Metro'],
            ['id' => 36, 'state_id' => 6, 'name' => 'NonMetro US'],
            ['id' => 37, 'state_id' => 7, 'name' => 'Bridgeport-Stamford-Norwalk CT Metro'],
            ['id' => 38, 'state_id' => 7, 'name' => 'Hartford-West Hartford-East Hartford CT Metro'],
            ['id' => 39, 'state_id' => 7, 'name' => 'New Haven-Milford CT Metro'],
            ['id' => 40, 'state_id' => 8, 'name' => 'Dover DE Metro'],
            ['id' => 41, 'state_id' => 8, 'name' => 'Salisbury MD-DE Metro'],
            ['id' => 42, 'state_id' => 8, 'name' => 'Wilmington DE-MD-NJ Metro Div.'],
            ['id' => 43, 'state_id' => 9, 'name' => 'Washington-Arlington-Alexandria DC-VA-MD-WV Metro Div.'],
            ['id' => 44, 'state_id' => 10, 'name' => 'Cape Coral-Fort Myers FL Metro'],
            ['id' => 45, 'state_id' => 10, 'name' => 'Deltona-Daytona Beach-Ormond Beach FL Metro'],
            ['id' => 46, 'state_id' => 10, 'name' => 'Fort Lauderdale-Pompano Beach-Deerfield Beach FL Metro Div.'],
            ['id' => 47, 'state_id' => 10, 'name' => 'Gainesville FL Metro'],
            ['id' => 48, 'state_id' => 10, 'name' => 'Jacksonville FL Metro'],
            ['id' => 49, 'state_id' => 10, 'name' => 'Miami-Miami Beach-Kendall FL Metro Div.'],
            ['id' => 50, 'state_id' => 10, 'name' => 'North Port-Sarasota-Bradenton FL Metro'],
            ['id' => 51, 'state_id' => 10, 'name' => 'Orlando-Kissimmee-Sanford FL Metro'],
            ['id' => 52, 'state_id' => 10, 'name' => 'Pensacola-Ferry Pass-Brent FL Metro'],
            ['id' => 53, 'state_id' => 10, 'name' => 'Sebastian-Vero Beach FL Metro'],
            ['id' => 54, 'state_id' => 10, 'name' => 'Tallahassee FL Metro'],
            ['id' => 55, 'state_id' => 10, 'name' => 'Tampa-St. Petersburg-Clearwater FL Metro'],
            ['id' => 56, 'state_id' => 11, 'name' => 'Albany GA Metro'],
            ['id' => 57, 'state_id' => 11, 'name' => 'Atlanta-Sandy Springs-Roswell GA Metro'],
            ['id' => 58, 'state_id' => 11, 'name' => 'Augusta-Richmond County GA-SC Metro'],
            ['id' => 59, 'state_id' => 11, 'name' => 'Dalton GA Metro'],
            ['id' => 60, 'state_id' => 11, 'name' => 'Dublin GA Micro'],
            ['id' => 61, 'state_id' => 11, 'name' => 'LaGrange GA Micro'],
            ['id' => 62, 'state_id' => 11, 'name' => 'Savannah GA Metro'],
            ['id' => 63, 'state_id' => 11, 'name' => 'Statesboro GA Micro'],
            ['id' => 64, 'state_id' => 11, 'name' => 'Valdosta GA Metro'],
            ['id' => 65, 'state_id' => 12, 'name' => 'Hilo HI Micro'],
            ['id' => 66, 'state_id' => 12, 'name' => 'Urban Honolulu HI Metro'],
            ['id' => 67, 'state_id' => 13, 'name' => 'Boise City ID Metro'],
            ['id' => 68, 'state_id' => 13, 'name' => 'Twin Falls ID Micro'],
            ['id' => 69, 'state_id' => 14, 'name' => 'Champaign-Urbana IL Metro'],
            ['id' => 70, 'state_id' => 14, 'name' => 'Chicago-Naperville-Arlington Heights IL Metro Div.'],
            ['id' => 71, 'state_id' => 14, 'name' => 'Danville IL Metro'],
            ['id' => 72, 'state_id' => 14, 'name' => 'Decatur IL Metro'],
            ['id' => 73, 'state_id' => 14, 'name' => 'Kankakee IL Metro'],
            ['id' => 74, 'state_id' => 14, 'name' => 'Peoria IL Metro'],
            ['id' => 75, 'state_id' => 14, 'name' => 'Rockford IL Metro'],
            ['id' => 76, 'state_id' => 14, 'name' => 'Springfield IL Metro'],
            ['id' => 77, 'state_id' => 15, 'name' => 'Bloomington IN Metro'],
            ['id' => 78, 'state_id' => 15, 'name' => 'Elkhart-Goshen IN Metro'],
            ['id' => 79, 'state_id' => 15, 'name' => 'Evansville IN-KY Metro'],
            ['id' => 80, 'state_id' => 15, 'name' => 'Fort Wayne IN Metro'],
            ['id' => 81, 'state_id' => 15, 'name' => 'Indianapolis-Carmel-Anderson IN Metro'],
            ['id' => 82, 'state_id' => 15, 'name' => 'Lafayette-West Lafayette IN Metro'],
            ['id' => 83, 'state_id' => 15, 'name' => 'Richmond IN Micro'],
            ['id' => 84, 'state_id' => 15, 'name' => 'South Bend-Mishawaka IN-MI Metro'],
            ['id' => 85, 'state_id' => 15, 'name' => 'Terre Haute IN Metro'],
            ['id' => 86, 'state_id' => 16, 'name' => 'Ames IA Metro'],
            ['id' => 87, 'state_id' => 16, 'name' => 'Burlington IA-IL Micro'],
            ['id' => 88, 'state_id' => 16, 'name' => 'Cedar Rapids IA Metro'],
            ['id' => 89, 'state_id' => 16, 'name' => 'Davenport-Moline-Rock Island IA-IL Metro'],
            ['id' => 90, 'state_id' => 16, 'name' => 'Des Moines-West Des Moines IA Metro'],
            ['id' => 91, 'state_id' => 16, 'name' => 'Dubuque IA Metro'],
            ['id' => 92, 'state_id' => 16, 'name' => 'Mason City IA Micro'],
            ['id' => 93, 'state_id' => 16, 'name' => 'Waterloo-Cedar Falls IA Metro'],
            ['id' => 94, 'state_id' => 17, 'name' => 'Dodge City KS Micro'],
            ['id' => 95, 'state_id' => 17, 'name' => 'Hutchinson KS Micro'],
            ['id' => 96, 'state_id' => 17, 'name' => 'Manhattan KS Metro'],
            ['id' => 97, 'state_id' => 17, 'name' => 'Pittsburg KS Micro'],
            ['id' => 98, 'state_id' => 17, 'name' => 'Salina KS Micro'],
            ['id' => 99, 'state_id' => 17, 'name' => 'Topeka KS Metro'],
            ['id' => 100, 'state_id' => 17, 'name' => 'Wichita KS Metro'],
            ['id' => 101, 'state_id' => 18, 'name' => 'Bowling Green KY Metro'],
            ['id' => 102, 'state_id' => 18, 'name' => 'Lexington-Fayette KY Metro'],
            ['id' => 103, 'state_id' => 18, 'name' => 'Louisville-Jefferson County KY-IN Metro'],
            ['id' => 104, 'state_id' => 19, 'name' => 'Alexandria LA Metro'],
            ['id' => 105, 'state_id' => 19, 'name' => 'Baton Rouge LA Metro'],
            ['id' => 106, 'state_id' => 19, 'name' => 'Hammond LA Metro'],
            ['id' => 107, 'state_id' => 19, 'name' => 'Houma-Thibodaux LA Metro'],
            ['id' => 108, 'state_id' => 19, 'name' => 'Lafayette LA Metro'],
            ['id' => 109, 'state_id' => 19, 'name' => 'Lake Charles LA Metro'],
            ['id' => 110, 'state_id' => 19, 'name' => 'Monroe LA Metro'],
            ['id' => 111, 'state_id' => 19, 'name' => 'New Orleans-Metairie LA Metro'],
            ['id' => 112, 'state_id' => 19, 'name' => 'Shreveport-Bossier City LA Metro'],
            ['id' => 113, 'state_id' => 20, 'name' => 'Portland-South Portland ME Metro'],
            ['id' => 114, 'state_id' => 21, 'name' => 'Baltimore-Columbia-Towson MD Metro'],
            ['id' => 115, 'state_id' => 21, 'name' => 'Silver Spring-Frederick-Rockville MD Metro Div.'],
            ['id' => 116, 'state_id' => 22, 'name' => 'Boston MA Metro Div.'],
            ['id' => 117, 'state_id' => 22, 'name' => 'Cambridge-Newton-Framingham MA Metro Div.'],
            ['id' => 118, 'state_id' => 22, 'name' => 'Pittsfield MA Metro'],
            ['id' => 119, 'state_id' => 23, 'name' => 'Detroit-Dearborn-Livonia MI Metro Div.'],
            ['id' => 120, 'state_id' => 23, 'name' => 'Grand Rapids-Wyoming MI Metro'],
            ['id' => 121, 'state_id' => 23, 'name' => 'Kalamazoo-Portage MI Metro'],
            ['id' => 122, 'state_id' => 23, 'name' => 'Niles-Benton Harbor MI '],
            ['id' => 123, 'state_id' => 24, 'name' => 'Mankato-North Mankato MN Metro'],
            ['id' => 124, 'state_id' => 24, 'name' => 'Minneapolis-St. Paul-Bloomington MN-WI Metro'],
            ['id' => 125, 'state_id' => 24, 'name' => 'St. Cloud MN Metro'],
            ['id' => 126, 'state_id' => 25, 'name' => 'Gulfport-Biloxi-Pascagoula MS Metro'],
            ['id' => 127, 'state_id' => 25, 'name' => 'Hattiesburg MS Metro'],
            ['id' => 128, 'state_id' => 25, 'name' => 'Jackson MS Metro'],
            ['id' => 129, 'state_id' => 25, 'name' => 'Tupelo MS Micro'],
            ['id' => 130, 'state_id' => 26, 'name' => 'Columbia MO Metro'],
            ['id' => 131, 'state_id' => 26, 'name' => 'Jefferson City MO Metro'],
            ['id' => 132, 'state_id' => 26, 'name' => 'Joplin MO Metro'],
            ['id' => 133, 'state_id' => 26, 'name' => 'Kansas City MO-KS Metro'],
            ['id' => 134, 'state_id' => 26, 'name' => 'St. Louis MO-IL Metro'],
            ['id' => 135, 'state_id' => 26, 'name' => 'Springfield MO Metro'],
            ['id' => 136, 'state_id' => 27, 'name' => 'Bozeman MT Micro'],
            ['id' => 137, 'state_id' => 28, 'name' => 'Hastings NE Micro'],
            ['id' => 138, 'state_id' => 28, 'name' => 'Lincoln NE Metro'],
            ['id' => 139, 'state_id' => 28, 'name' => 'Omaha-Council Bluffs NE-IA Metro'],
            ['id' => 140, 'state_id' => 29, 'name' => 'Las Vegas-Henderson-Paradise NV Metro'],
            ['id' => 141, 'state_id' => 29, 'name' => 'Reno NV Metro'],
            ['id' => 142, 'state_id' => 30, 'name' => 'Manchester-Nashua NH Metro'],
            ['id' => 143, 'state_id' => 31, 'name' => 'Newark NJ-PA Metro Div.'],
            ['id' => 144, 'state_id' => 31, 'name' => 'New York-Jersey City-White Plains NY-NJ Metro Div.'],
            ['id' => 145, 'state_id' => 32, 'name' => 'Albuquerque NM Metro'],
            ['id' => 146, 'state_id' => 32, 'name' => 'Las Cruces NM Metro'],
            ['id' => 147, 'state_id' => 33, 'name' => 'Albany-Schenectady-Troy NY Metro'],
            ['id' => 148, 'state_id' => 33, 'name' => 'Buffalo-Cheektowaga-Niagara Falls NY Metro'],
            ['id' => 149, 'state_id' => 33, 'name' => 'Ithaca NY Metro'],
            ['id' => 150, 'state_id' => 33, 'name' => 'New York-Jersey City-White Plains NY-NJ Metro Div.'],
            ['id' => 151, 'state_id' => 33, 'name' => 'Rochester NY Metro'],
            ['id' => 152, 'state_id' => 33, 'name' => 'Utica-Rome NY Metro'],
            ['id' => 153, 'state_id' => 34, 'name' => 'Asheville NC Metro'],
            ['id' => 154, 'state_id' => 34, 'name' => 'Burlington NC Metro'],
            ['id' => 155, 'state_id' => 34, 'name' => 'Charlotte-Concord-Gastonia NC-SC Metro'],
            ['id' => 156, 'state_id' => 34, 'name' => 'Durham-Chapel Hill NC Metro'],
            ['id' => 157, 'state_id' => 34, 'name' => 'Kill Devil Hills NC Micro'],
            ['id' => 158, 'state_id' => 34, 'name' => 'Raleigh NC Metro'],
            ['id' => 159, 'state_id' => 34, 'name' => 'Wilmington NC Metro'],
            ['id' => 160, 'state_id' => 34, 'name' => 'Winston-Salem NC Metro'],
            ['id' => 161, 'state_id' => 35, 'name' => 'Bismarck ND Metro'],
            ['id' => 162, 'state_id' => 35, 'name' => 'Fargo ND-MN Metro'],
            ['id' => 163, 'state_id' => 35, 'name' => 'Grand Forks ND-MN Metro'],
            ['id' => 164, 'state_id' => 35, 'name' => 'Minot ND Micro'],
            ['id' => 165, 'state_id' => 36, 'name' => 'Akron OH Metro'],
            ['id' => 166, 'state_id' => 36, 'name' => 'Ashland OH Micro'],
            ['id' => 167, 'state_id' => 36, 'name' => 'Cincinnati OH-KY-IN Metro'],
            ['id' => 168, 'state_id' => 36, 'name' => 'Cleveland-Elyria OH Metro'],
            ['id' => 169, 'state_id' => 36, 'name' => 'Columbus OH Metro'],
            ['id' => 170, 'state_id' => 36, 'name' => 'Dayton OH Metro'],
            ['id' => 171, 'state_id' => 36, 'name' => 'Findlay OH Micro'],
            ['id' => 172, 'state_id' => 36, 'name' => 'Lima OH Metro'],
            ['id' => 173, 'state_id' => 37, 'name' => 'Ardmore OK Micro'],
            ['id' => 174, 'state_id' => 37, 'name' => 'Enid OK Micro'],
            ['id' => 175, 'state_id' => 37, 'name' => 'Lawton OK Metro'],
            ['id' => 176, 'state_id' => 37, 'name' => 'Muskogee OK Micro'],
            ['id' => 177, 'state_id' => 37, 'name' => 'Oklahoma City OK Metro'],
            ['id' => 178, 'state_id' => 37, 'name' => 'Ponca City OK Micro'],
            ['id' => 179, 'state_id' => 37, 'name' => 'Tulsa OK Metro'],
            ['id' => 180, 'state_id' => 37, 'name' => 'NonMetro US'],
            ['id' => 181, 'state_id' => 38, 'name' => 'Portland-Vancouver-Hillsboro OR-WA Metro'],
            ['id' => 182, 'state_id' => 39, 'name' => 'Allentown-Bethlehem-Easton PA-NJ Metro'],
            ['id' => 183, 'state_id' => 39, 'name' => 'Harrisburg-Carlisle PA Metro'],
            ['id' => 184, 'state_id' => 39, 'name' => 'Philadelphia PA Metro Div.'],
            ['id' => 185, 'state_id' => 39, 'name' => 'Pittsburgh PA Metro'],
            ['id' => 186, 'state_id' => 39, 'name' => 'Scranton-Wilkes-Barre-Hazleton PA Metro'],
            ['id' => 187, 'state_id' => 39, 'name' => 'York-Hanover PA Metro'],
            ['id' => 188, 'state_id' => 40, 'name' => 'Providence-Warwick RI-MA Metro'],
            ['id' => 189, 'state_id' => 41, 'name' => 'Charleston-North Charleston SC Metro'],
            ['id' => 190, 'state_id' => 41, 'name' => 'Columbia SC Metro'],
            ['id' => 191, 'state_id' => 41, 'name' => 'Greenville-Anderson-Mauldin SC Metro'],
            ['id' => 192, 'state_id' => 41, 'name' => 'Hilton Head Island-Bluffton-Beaufort SC Metro'],
            ['id' => 193, 'state_id' => 42, 'name' => 'Pierre SD Micro'],
            ['id' => 194, 'state_id' => 42, 'name' => 'Sioux Falls SD Metro'],
            ['id' => 195, 'state_id' => 43, 'name' => 'Chattanooga TN-GA Metro'],
            ['id' => 196, 'state_id' => 43, 'name' => 'Clarksville TN-KY Metro'],
            ['id' => 197, 'state_id' => 43, 'name' => 'Cleveland TN Metro'],
            ['id' => 198, 'state_id' => 43, 'name' => 'Cookeville TN Micro'],
            ['id' => 199, 'state_id' => 43, 'name' => 'Jackson TN Metro'],
            ['id' => 200, 'state_id' => 43, 'name' => 'Knoxville TN Metro'],
            ['id' => 201, 'state_id' => 43, 'name' => 'Memphis TN-MS-AR Metro'],
            ['id' => 202, 'state_id' => 43, 'name' => 'Morristown TN Metro'],
            ['id' => 203, 'state_id' => 43, 'name' => 'Nashville-Davidson-Murfreesboro-Franklin TN Metro'],
            ['id' => 204, 'state_id' => 44, 'name' => 'Abilene TX Metro'],
            ['id' => 205, 'state_id' => 44, 'name' => 'Amarillo TX Metro'],
            ['id' => 206, 'state_id' => 44, 'name' => 'Austin-Round Rock TX Metro'],
            ['id' => 207, 'state_id' => 44, 'name' => 'Beaumont-Port Arthur TX Metro'],
            ['id' => 208, 'state_id' => 44, 'name' => 'Brownsville-Harlingen TX Metro'],
            ['id' => 209, 'state_id' => 44, 'name' => 'Corpus Christi TX Metro'],
            ['id' => 210, 'state_id' => 44, 'name' => 'Dallas-Plano-Irving Metro Metro Div.'],
            ['id' => 211, 'state_id' => 44, 'name' => 'El Paso TX Metro'],
            ['id' => 212, 'state_id' => 44, 'name' => 'Fort Worth-Arlington TX Metro Div.'],
            ['id' => 213, 'state_id' => 44, 'name' => 'Houston-The Woodlands-Sugar Land TX Metro'],
            ['id' => 214, 'state_id' => 44, 'name' => 'Killeen-Temple TX Metro'],
            ['id' => 215, 'state_id' => 44, 'name' => 'Longview TX Metro'],
            ['id' => 216, 'state_id' => 44, 'name' => 'Lubbock TX Metro'],
            ['id' => 217, 'state_id' => 44, 'name' => 'McAllen-Edinburg-Mission TX Metro'],
            ['id' => 218, 'state_id' => 44, 'name' => 'Midland TX Metro'],
            ['id' => 219, 'state_id' => 44, 'name' => 'Nacogdoches TX Micro'],
            ['id' => 220, 'state_id' => 44, 'name' => 'Odessa TX Metro'],
            ['id' => 221, 'state_id' => 44, 'name' => 'San Antonio-New Braunfels TX Metro'],
            ['id' => 222, 'state_id' => 44, 'name' => 'Sherman-Denison TX Metro'],
            ['id' => 223, 'state_id' => 44, 'name' => 'Texarkana TX-AR Metro'],
            ['id' => 224, 'state_id' => 44, 'name' => 'Tyler TX Metro'],
            ['id' => 225, 'state_id' => 44, 'name' => 'Waco TX Metro'],
            ['id' => 226, 'state_id' => 44, 'name' => 'Wichita Falls TX Metro'],
            ['id' => 227, 'state_id' => 45, 'name' => 'Cedar City UT Micro'],
            ['id' => 228, 'state_id' => 45, 'name' => 'Ogden-Clearfield UT Metro'],
            ['id' => 229, 'state_id' => 45, 'name' => 'Provo-Orem UT Metro'],
            ['id' => 230, 'state_id' => 45, 'name' => 'St. George UT Metro'],
            ['id' => 231, 'state_id' => 45, 'name' => 'Salt Lake City UT Metro'],
            ['id' => 232, 'state_id' => 46, 'name' => 'Burlington-South Burlington VT Metro'],
            ['id' => 233, 'state_id' => 47, 'name' => 'Blacksburg-Christiansburg-Radford VA Metro'],
            ['id' => 234, 'state_id' => 47, 'name' => 'Charlottesville VA Metro'],
            ['id' => 235, 'state_id' => 47, 'name' => 'Danville VA Micro'],
            ['id' => 236, 'state_id' => 47, 'name' => 'Harrisonburg VA Metro'],
            ['id' => 237, 'state_id' => 47, 'name' => 'Lynchburg VA Metro'],
            ['id' => 238, 'state_id' => 47, 'name' => 'Martinsville VA Micro'],
            ['id' => 239, 'state_id' => 47, 'name' => 'Richmond VA Metro'],
            ['id' => 240, 'state_id' => 47, 'name' => 'Roanoke VA Metro'],
            ['id' => 241, 'state_id' => 47, 'name' => 'Staunton-Waynesboro VA Metro'],
            ['id' => 242, 'state_id' => 47, 'name' => 'Virginia Beach-Norfolk-Newport News VA-NC Metro'],
            ['id' => 243, 'state_id' => 47, 'name' => 'Washington-Arlington-Alexandria DC-VA-MD-WV Metro Div.'],
            ['id' => 244, 'state_id' => 47, 'name' => 'Winchester VA-WV Metro'],
            ['id' => 245, 'state_id' => 47, 'name' => 'NonMetro US'],
            ['id' => 246, 'state_id' => 48, 'name' => 'Bellingham WA Metro'],
            ['id' => 247, 'state_id' => 48, 'name' => 'Kennewick-Richland WA Metro'],
            ['id' => 248, 'state_id' => 48, 'name' => 'Moses Lake WA Micro'],
            ['id' => 249, 'state_id' => 48, 'name' => 'Mount Vernon-Anacortes WA Metro'],
            ['id' => 250, 'state_id' => 48, 'name' => 'Olympia-Tumwater WA Metro'],
            ['id' => 251, 'state_id' => 48, 'name' => 'Seattle-Bellevue-Everett WA Metro Div.'],
            ['id' => 252, 'state_id' => 48, 'name' => 'Spokane-Spokane Valley WA Metro'],
            ['id' => 253, 'state_id' => 48, 'name' => 'Tacoma-Lakewood WA Metro Div.'],
            ['id' => 254, 'state_id' => 48, 'name' => 'Wenatchee WA Metro'],
            ['id' => 255, 'state_id' => 48, 'name' => 'Yakima WA Metro'],
            ['id' => 256, 'state_id' => 49, 'name' => 'Morgantown WV Metro'],
            ['id' => 257, 'state_id' => 50, 'name' => 'Eau Claire WI Metro'],
            ['id' => 258, 'state_id' => 50, 'name' => 'Fond du Lac WI Metro'],
            ['id' => 259, 'state_id' => 50, 'name' => 'Green Bay WI Metro'],
            ['id' => 260, 'state_id' => 50, 'name' => 'Madison WI Metro'],
            ['id' => 261, 'state_id' => 50, 'name' => 'Milwaukee-Waukesha-West Allis WI Metro'],
            ['id' => 262, 'state_id' => 50, 'name' => 'Wisconsin Rapids-Marshfield WI Micro'],
            ['id' => 263, 'state_id' => 51, 'name' => 'Cheyenne WY Metro'],
            ['id' => 264, 'state_id' => 51, 'name' => 'Laramie WY Micro'],
            ['id' => 265, 'state_id' => 52, 'name' => 'San Juan-Carolina-Caguas  PR Metro'],
        ];
    }
}
